version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: carfix_db
      POSTGRES_USER: carfix_user
      POSTGRES_PASSWORD: jihug7aa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .


    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate --run-syncdb &&
        python manage.py migrate --noinput &&

        python manage.py shell -c 'from django.contrib.auth import get_user_model; import os; User = get_user_model(); u, created = User.objects.get_or_create(username=os.environ[\"DJANGO_SUPERUSER_USERNAME\"], defaults={\"email\": \"\", \"is_staff\": True, \"is_superuser\": True}); u.set_password(os.environ[\"DJANGO_SUPERUSER_PASSWORD\"]); u.save()' &&

        exec gunicorn car_fix_control_system.wsgi:application --bind 0.0.0.0:8000
      "


      
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
